### ISSUE TITLE
Seq is rejecting payloads with numbers

### ISSUE THREAD

**Issue by DanAvni** [datalust/seq-tickets#1191]
if you declare a double variable and assign it a value of 8.2535170109512364E+28 then try to log this seq rejects the payload with this message

```
[2021-04-12T11:52:38.8713351+03:00 DBG] Rejecting payload from 127.0.0.1 due to invalid JSON, request body could not be parsed
Newtonsoft.Json.JsonReaderException: Input string '8.2535170109512364E+28' is not a valid decimal. Path 'Events[1].Properties.Cost', line 1, position 743.
   at Newtonsoft.Json.JsonTextReader.ParseReadNumber(ReadType readType, Char firstChar, Int32 initialPosition)
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonWriter.WriteToken(JsonReader reader, Boolean writeChildren, Boolean writeDateConstructorAsDate, Boolean writeComments)
   at Newtonsoft.Json.JsonWriter.WriteToken(JsonReader reader, Boolean writeChildren)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateJToken(JsonReader reader, JsonContract contract)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   at Seq.Server.Web.Api.IngestionController.TryParseRawFormatBody(Input input, InputSettings inputSettings, StorageEventCreationData[]& events, String& errorMessage)
```

**Comment by nblumhardt** [comment]
Thanks, Dani 👍

**Comment by nblumhardt** [comment]
This is very similar to #496, which addresses a similar issue deeper in the ingestion process by converting any floating point too big to fit Seq's underlying `decimal` numeric representation into a string.

Later Seq versions switched to using `decimal` handling for floating point values right out in the ingestion API to avoid loss of precision due to floating point handling. I'm not sure what the intended/original behavior was in this case, it seems unlikely we'd have missed it entirely... More investigation required... 🤔
