### ISSUE TITLE
Uninformative error message on start-up when `SEQ_FIRSTRUN_ADMINPASSWORDHASH` is invalid

### ISSUE THREAD

**Issue by kpspence** [datalust/seq-tickets#1219]
Fatal exception running docker container on Oracle Linux Server 7.9.  Same image/command works fine in Docker on Windows 10 machine.

```
Application startup exception: Autofac.Core.DependencyResolutionException: An exception was thrown while activating Î»:Seq.Cluster.IClusterNode -> Î»:Seq.Server.StorageSubsystem.
 ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
```

Docker Command
```
docker run --name seqtest \
--restart unless-stopped \
-e ACCEPT_EULA=Y \
-e SEQ_FIRSTRUN_ADMINPASSWORDHASH="$PH" \
-v /tmp:/data \
-p 80:80 \
-p 5341:5341 \
-e RUST_BACKTRACE=1 \
datalust/seq
```

System/Docker Information
```
$ cat /etc/oracle-release
Oracle Linux Server release 7.9
$
$ docker version
Client: Docker Engine - Community
 Version:           19.03.11-ol
 API version:       1.40
 Go version:        go1.15.5
 Git commit:        748876d
 Built:             Thu Dec  3 19:36:03 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.11-ol
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.15.5
  Git commit:       748876d
  Built:            Thu Dec  3 19:34:21 2020
  OS/Arch:          linux/amd64
  Experimental:     false
  Default Registry: docker.io
 containerd:
  Version:          v1.3.9
  GitCommit:
 runc:
  Version:          1.0.0-rc5+dev
  GitCommit:        4bb1fe4ace1a32d3676bb98f5d3b6a4e32bf6c58
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

Seq log file
```
ââââââââââââââââââââââââââââââââââââââââ
  Seq â¦ Machine data, for humans.
âââââââââââ Â© 2021 Datalust Pty Ltd ââââ

Running as server; press Ctrl+C to exit.

[22:50:06 INF] Seq "2021.2.5647" running on OS "Linux 4.14.35-2025.404.1.1.el7uek.x86_64 #2 SMP Tue Jan 5 12:57:13 PST 2021"
[22:50:06 INF] Seq detected 16507.121664 MB of RAM
[22:50:06 INF] Opening event store at "/data/Stream/stream.flare"
[22:50:06 INF] Opening metastore "/data/Documents/documents.lmdb"
[22:50:06 INF] Applying migration "Create the Administrator account"
[22:50:06 INF] Enabling username/password authentication, and using the supplied default admin password or hash
[22:50:06 INF] Closing metastore
[22:50:06 INF] Closing event store
Application startup exception: Autofac.Core.DependencyResolutionException: An exception was thrown while activating Î»:Seq.Cluster.IClusterNode -> Î»:Seq.Server.StorageSubsystem.
 ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Seq.Server.Config.Encoding.Base64SaltedHashEncoding.FromBase64(String base64)
   at Seq.Server.Data.Users.Migrations.CreateAdminUser.Apply(DocumentSession session)
   at Quince.Storage.Lmdb.LmdbDocumentStore.Migrate(IEnumerable`1 migrations)
   at Seq.Server.StorageSubsystem.Initialize(IComponentContext ctx, SeqConfig config, String instanceName, String storageRootPath, String nodeStateFilePath, String streamPath, String documentsPath)
   at Seq.Server.SeqServerModule.<Load>b__14_7(IComponentContext c)
   at Autofac.RegistrationExtensions.<>c__DisplayClass4_0`1.<Register>b__0(IComponentContext c, IEnumerable`1 p)
   at Autofac.Builder.RegistrationBuilder.<>c__DisplayClass0_0`1.<ForDelegate>b__0(IComponentContext c, IEnumerable`1 p)
   at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.CreateInstance(IEnumerable`1 parameters)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.InstanceLookup.CreateInstance(IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, ResolveRequest request)
   at Autofac.Core.Resolving.ResolveOperation.ResolveComponent(ResolveRequest request)
   at Autofac.Core.Resolving.ResolveOperation.Execute(ResolveRequest request)
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(ResolveRequest request)
   at Autofac.Core.Container.ResolveComponent(ResolveRequest request)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveOptionalService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.ResolveOptional(IComponentContext context, Type serviceType, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.ResolveOptional(IComponentContext context, Type serviceType)
   at Autofac.Extensions.DependencyInjection.AutofacServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass5_0.<UseMiddleware>b__0(RequestDelegate next)
   at Microsoft.AspNetCore.Builder.ApplicationBuilder.Build()
   at Microsoft.AspNetCore.Hosting.WebHost.BuildApplication()
[22:50:06 FTL] Application startup exception
Autofac.Core.DependencyResolutionException: An exception was thrown while activating Î»:Seq.Cluster.IClusterNode -> Î»:Seq.Server.StorageSubsystem.
 ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Seq.Server.Config.Encoding.Base64SaltedHashEncoding.FromBase64(String base64)
   at Seq.Server.Data.Users.Migrations.CreateAdminUser.Apply(DocumentSession session)
   at Quince.Storage.Lmdb.LmdbDocumentStore.Migrate(IEnumerable`1 migrations)
   at Seq.Server.StorageSubsystem.Initialize(IComponentContext ctx, SeqConfig config, String instanceName, String storageRootPath, String nodeStateFilePath, String streamPath, String documentsPath)
   at Seq.Server.SeqServerModule.<Load>b__14_7(IComponentContext c)
   at Autofac.RegistrationExtensions.<>c__DisplayClass4_0`1.<Register>b__0(IComponentContext c, IEnumerable`1 p)
   at Autofac.Builder.RegistrationBuilder.<>c__DisplayClass0_0`1.<ForDelegate>b__0(IComponentContext c, IEnumerable`1 p)
   at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.CreateInstance(IEnumerable`1 parameters)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.InstanceLookup.CreateInstance(IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, ResolveRequest request)
   at Autofac.Core.Resolving.ResolveOperation.ResolveComponent(ResolveRequest request)
   at Autofac.Core.Resolving.ResolveOperation.Execute(ResolveRequest request)
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(ResolveRequest request)
   at Autofac.Core.Container.ResolveComponent(ResolveRequest request)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveOptionalService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.ResolveOptional(IComponentContext context, Type serviceType, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.ResolveOptional(IComponentContext context, Type serviceType)
   at Autofac.Extensions.DependencyInjection.AutofacServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass5_0.<UseMiddleware>b__0(RequestDelegate next)
   at Microsoft.AspNetCore.Builder.ApplicationBuilder.Build()
   at Microsoft.AspNetCore.Hosting.WebHost.BuildApplication()
[22:50:06 FTL] Error running the server application
Autofac.Core.DependencyResolutionException: An exception was thrown while activating Î»:Seq.Cluster.IClusterNode -> Î»:Seq.Server.StorageSubsystem.
 ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Seq.Server.Config.Encoding.Base64SaltedHashEncoding.FromBase64(String base64)
   at Seq.Server.Data.Users.Migrations.CreateAdminUser.Apply(DocumentSession session)
   at Quince.Storage.Lmdb.LmdbDocumentStore.Migrate(IEnumerable`1 migrations)
   at Seq.Server.StorageSubsystem.Initialize(IComponentContext ctx, SeqConfig config, String instanceName, String storageRootPath, String nodeStateFilePath, String streamPath, String documentsPath)
   at Seq.Server.SeqServerModule.<Load>b__14_7(IComponentContext c)
   at Autofac.RegistrationExtensions.<>c__DisplayClass4_0`1.<Register>b__0(IComponentContext c, IEnumerable`1 p)
   at Autofac.Builder.RegistrationBuilder.<>c__DisplayClass0_0`1.<ForDelegate>b__0(IComponentContext c, IEnumerable`1 p)
   at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.CreateInstance(IEnumerable`1 parameters)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.InstanceLookup.CreateInstance(IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, ResolveRequest request)
   at Autofac.Core.Resolving.ResolveOperation.ResolveComponent(ResolveRequest request)
   at Autofac.Core.Resolving.ResolveOperation.Execute(ResolveRequest request)
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(ResolveRequest request)
   at Autofac.Core.Container.ResolveComponent(ResolveRequest request)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveOptionalService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.ResolveOptional(IComponentContext context, Type serviceType, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.ResolveOptional(IComponentContext context, Type serviceType)
   at Autofac.Extensions.DependencyInjection.AutofacServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass5_0.<UseMiddleware>b__0(RequestDelegate next)
   at Microsoft.AspNetCore.Builder.ApplicationBuilder.Build()
   at Microsoft.AspNetCore.Hosting.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHost.Start()
   at Seq.Server.ServiceProcess.ServerService.Start()
[22:50:06 FTL] Failed to start server
Autofac.Core.DependencyResolutionException: An exception was thrown while activating Î»:Seq.Cluster.IClusterNode -> Î»:Seq.Server.StorageSubsystem.
 ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Seq.Server.Config.Encoding.Base64SaltedHashEncoding.FromBase64(String base64)
   at Seq.Server.Data.Users.Migrations.CreateAdminUser.Apply(DocumentSession session)
   at Quince.Storage.Lmdb.LmdbDocumentStore.Migrate(IEnumerable`1 migrations)
   at Seq.Server.StorageSubsystem.Initialize(IComponentContext ctx, SeqConfig config, String instanceName, String storageRootPath, String nodeStateFilePath, String streamPath, String documentsPath)
   at Seq.Server.SeqServerModule.<Load>b__14_7(IComponentContext c)
   at Autofac.RegistrationExtensions.<>c__DisplayClass4_0`1.<Register>b__0(IComponentContext c, IEnumerable`1 p)
   at Autofac.Builder.RegistrationBuilder.<>c__DisplayClass0_0`1.<ForDelegate>b__0(IComponentContext c, IEnumerable`1 p)
   at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.CreateInstance(IEnumerable`1 parameters)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.InstanceLookup.CreateInstance(IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, ResolveRequest request)
   at Autofac.Core.Resolving.ResolveOperation.ResolveComponent(ResolveRequest request)
   at Autofac.Core.Resolving.ResolveOperation.Execute(ResolveRequest request)
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(ResolveRequest request)
   at Autofac.Core.Container.ResolveComponent(ResolveRequest request)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveOptionalService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.ResolveOptional(IComponentContext context, Type serviceType, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.ResolveOptional(IComponentContext context, Type serviceType)
   at Autofac.Extensions.DependencyInjection.AutofacServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass5_0.<UseMiddleware>b__0(RequestDelegate next)
   at Microsoft.AspNetCore.Builder.ApplicationBuilder.Build()
   at Microsoft.AspNetCore.Hosting.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHost.Start()
   at Seq.Server.ServiceProcess.ServerService.Start()
   at Seq.Server.Cli.RunCommand.RunStandardIOAsync(Func`1 bootstrap, TextWriter cout)
```

**Comment by nblumhardt** [comment]
Thanks for the report! We'll take a look and let you know what we find.

**Comment by nblumhardt** [comment]
Hi @kpspence - hope you had a good weekend.

It looks like the value of `SEQ_FIRSTRUN_ADMINPASSWORDHASH` is invalid (terrible error message from Seq here - fixing it as we speak!).

The value needs to be generated using something like `docker run datalust/seq config hash`, and can't (for example) be the password itself.

Let me know if this helps! 🤞

**Comment by kpspence** [comment]
That worked.  Thank you.  I was so focused on the error message that I never noticed that configuration mistake.

**Comment by nblumhardt** [comment]
Great - thanks!
