### ISSUE TITLE
Seq on docker on Windows Server Core failed to start server

### ISSUE THREAD

**Issue by zwolenik** [datalust/seq-tickets#1393]
**Describe the bug**
I have working and running Seq in docker on Windows Server Core.
From several hours Seq server started restarting with following error:

`
[12:12:41 FTL] Failed to start server
Autofac.Core.DependencyResolutionException: An exception was thrown while activating λ:Seq.Cluster.IClusterNode -> λ:Seq.Server.StorageSubsystem.
 ---> LightningDB 0: Failed to open environment at path /data/Documents/documents.lmdb
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.InstanceLookup.CreateInstance(IEnumerable``1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, ResolveRequest request)
   at Autofac.Core.Resolving.ResolveOperation.ResolveComponent(ResolveRequest request)
   at Autofac.Core.Resolving.ResolveOperation.Execute(ResolveRequest request)
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(ResolveRequest request)
   at Autofac.Core.Container.ResolveComponent(ResolveRequest request)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable``1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveOptionalService(IComponentContext context, Service service, IEnumerable``1 parameters)
   at Autofac.ResolutionExtensions.ResolveOptional(IComponentContext context, Type serviceType, IEnumerable``1 parameters)
   at Autofac.ResolutionExtensions.ResolveOptional(IComponentContext context, Type serviceType)
   at Autofac.Extensions.DependencyInjection.AutofacServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass5_0.<UseMiddleware>b__0(RequestDelegate next)
   at Microsoft.AspNetCore.Builder.ApplicationBuilder.Build()
   at Microsoft.AspNetCore.Hosting.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHost.Start()
   at Seq.Server.ServiceProcess.ServerService.Start()
   at Seq.Server.Cli.RunCommand.RunStandardIOAsync(Func``1 bootstrap, TextWriter cout)
`

**Environment (please complete the following information):**
 - OS: Windows Server Core
 - Browser N/A
 - Seq Version latest
 - Using Docker? Yes

**Comment by nblumhardt** [comment]
Hi!

It sounds like you've encountered some form of file corruption or locking issue; these sometimes appear when Seq data is stored on a network filesystem (or other filesystem with quirky fsync). Can you send any further info on the disk backing the storage?

It's also possible, if the data is on a local volume that's mounted into the container, that another process (or AV) is interfering with the file.

A diagnostic report from _Settings > Diagnostics > Download a full diagnostic report_ might also help shed some light on what went wrong (please email this to support@ rather than posting here :-))

I'll follow up shortly with recovery instructions (just assembling some scripts).

**Comment by nblumhardt** [comment]
Before beginning recovery, I'd recommend taking a copy of `/data/Backups`, `/data/Documents`, and `/data/Seq.json`, just in case something goes wrong.

It's also worth double-checking that you're running 2021.3, as these instructions won't work for earlier versions.

The container needs to be stopped while you copy in the init script below, in case it reloads before the complete script is written to disk.

To recover, you'll need to add a script to the `Init` directory under the mounted `/data` volume; it can have any name, but `recover.sh` would be suitable; its contents are:

```sh
#!/bin/bash

# Make sure there's a backup available
if [ -z "$(ls -A /data/Backups)" ]; then
   echo "No backups available?"
   exit 1
fi

# Delete files belonging to the corrupted LMDB metastore
rm /data/Documents/*

# Give Seq 10 seconds to initialize a new, blank metastore.
# This won't be necessary from 2021.4 onwards.
timeout 10 "seqsvr run"

# Restore the latest backup.
seqsvr restore --from-latest --confirm
```

Then, restart the container; Seq will run `recover.sh` and then start up as usual.

If you notice any problems, please contact us via `support@`, as we'll notice that more quickly than if you follow up here.

Hope this helps!

**Comment by nblumhardt** [comment]
Hope this went well! Closing as two weeks have passed, but please let us know if you need further help with it.
