### ISSUE TITLE
docker image datalust/seq:latest does not start

### ISSUE THREAD

**Issue by feckardt** [datalust/seq-tickets#1754]
**Describe the bug**
Trying to start a docker container with:
`docker run --name seq -e ACCEPT_EULA=Y -p 5341:80 datalust/seq:latest`

**Expected behavior**
The container should start and the service listen on port 5341:80

**Error Messages during startup**
```
Unable to find image 'datalust/seq:latest' locally
b22d1486ce2c: Download complete
85516a362dc6: Download complete
afe39a95fc26: Download complete
a172d861c396: Download complete
25d7b07c03f8: Download complete
98864bde964c: Download complete
9945d6b28f53: Download complete
bdec8b63443a: Download complete
fab854d72efd: Download complete
8a595b9d5306: Download complete
────────────────────────────────────────
  Seq ♦ Machine data, for humans.
─────────── © 2023 Datalust Pty Ltd ────

Running as server; press Ctrl+C to exit.

[13:57:59 INF] Seq "2023.1.8829" running on OS "Linux 5.15.83.1-microsoft-standard-WSL2 #1 SMP Wed Dec 14 23:16:32 UTC 2022"
[13:57:59 INF] Seq detected 33590.378496 MB of RAM
[13:57:59 INF] Opening event store at "/data/Stream/stream.flare"
[13:57:59 INF] Ingestion enabled
[13:57:59 INF] Opening metastore "/data/Documents/metastore.flare"
[13:57:59 INF] Initializing a new metastore
[13:57:59 INF] Creating default workspace for "user-admin"
[13:57:59 INF] Storage subsystem available
[13:57:59 FTL] Error running the server application
System.IO.IOException: Failed to bind to address http://0.0.0.0:443: address already in use.
 ---> Microsoft.AspNetCore.Connections.AddressInUseException: Address already in use
 ---> System.Net.Sockets.SocketException (98): Address already in use
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportOptions.CreateDefaultBoundListenSocket(EndPoint endpoint)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportManager.BindAsync(EndPoint endPoint, ConnectionDelegate connectionDelegate, EndpointConfig endpointConfig, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<>c__DisplayClass30_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.EndpointsStrategy.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IEnumerable`1 listenOptions, AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHost.Start()
   at Seq.Server.ServiceProcess.ServerService.Start()
[13:57:59 FTL] Failed to start server
System.IO.IOException: Failed to bind to address http://0.0.0.0:443: address already in use.
 ---> Microsoft.AspNetCore.Connections.AddressInUseException: Address already in use
 ---> System.Net.Sockets.SocketException (98): Address already in use
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportOptions.CreateDefaultBoundListenSocket(EndPoint endpoint)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportManager.BindAsync(EndPoint endPoint, ConnectionDelegate connectionDelegate, EndpointConfig endpointConfig, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<>c__DisplayClass30_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.EndpointsStrategy.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IEnumerable`1 listenOptions, AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHost.Start()
   at Seq.Server.ServiceProcess.ServerService.Start()
   at Seq.Server.Cli.RunCommand.RunStandardIOAsync(Func`1 bootstrap, TextWriter cout)
```

**Environment (please complete the following information):**
 - OS: Windows
 - Docker Enginev20.10.22
 - Seq Version latest, 2022, 2021
 - Using Docker? Yes 

**Additional context**
`docker run --name seq -e ACCEPT_EULA=Y -p 5341:80 datalust/seq:2020` works fine.

**Comment by nblumhardt** [comment]
Thanks for dropping us a line, Frank!

Does `docker ps` show any other running containers when you're hitting the failure? This error would be typical of another Docker process on your WSL2 VM having bound port 443, I think - the port mapping and the ports listened on by Seq are separately configured, and by default the container will listen on 80, 443, 5341 and 45341.

2020 will be succeeding because it pre-dates SSL termination support in the `datalust/seq` container.

In any case, you can override the listen URIs to specify 80 only by adding:

```
-e SEQ_API_LISTENURIS=http://localhost:80
```

to the `docker run` command line.

Hope this helps,
Nick

**Comment by nblumhardt** [comment]
Hi again; I'll close this under the assumption that the suggestion above has resolved this for you. If you're still experiencing issues please just let us know.
