### ISSUE TITLE
Cannot install application from Azure Artifacts feed

### ISSUE THREAD

**Issue by MaceWindu** [datalust/seq-tickets#1872]
**Describe the bug**

When I'm trying to install Seq app nuget from Azure Artifacts feed it fails with following error:

```
2023-06-19 18:08:42 [16:08:42 INF] NuGet v3 GET https://pkgs.dev.azure.com/macewindu/projects/_packaging/projects/nuget/v3/index.json
2023-06-19 18:08:43 [16:08:43 INF] NuGet v3 GET https://pkgs.dev.azure.com/macewindu/d119c8d5-d981-4087-b983-65c3339155a0/_packaging/8c90a52a-2539-4e08-84e4-05beb440b781/nuget/v3/registrations2-semver2/seq.app.teams.adaptivecard/index.json
2023-06-19 18:08:43 [16:08:43 INF] NuGet v3 GET https://pkgs.dev.azure.com/macewindu/projects/_packaging/projects/nuget/v3/index.json
2023-06-19 18:08:43 [16:08:43 INF] NuGet v3 GET https://pkgs.dev.azure.com/macewindu/d119c8d5-d981-4087-b983-65c3339155a0/_packaging/8c90a52a-2539-4e08-84e4-05beb440b781/nuget/v3/registrations2-semver2/seq.app.teams.adaptivecard/index.json
2023-06-19 18:08:44 [16:08:44 INF] NuGet v3 GET https://pkgs.dev.azure.com/macewindu/d119c8d5-d981-4087-b983-65c3339155a0/_apis/packaging/8c90a52a-2539-4e08-84e4-05beb440b781/nuget/commitLog/05b6e714331c4d5393fc951745850127
2023-06-19 18:08:44 [16:08:44 INF] NuGet v3 GET https://pkgs.dev.azure.com/macewindu/d119c8d5-d981-4087-b983-65c3339155a0/_packaging/8c90a52a-2539-4e08-84e4-05beb440b781/nuget/v3/flat2/seq.app.teams.adaptivecard/1.0.0-rc.67/seq.app.teams.adaptivecard.1.0.0-rc.67.nupkg
2023-06-19 18:08:44 [16:08:44 ERR] Unable to install package Seq.App.Teams.AdaptiveCard vnull from nugetfeed-438
2023-06-19 18:08:44 System.IO.InvalidDataException: Central Directory corrupt.
2023-06-19 18:08:44  ---> System.IO.IOException: Invalid argument : '/data/Packages/nugetfeed-438/Seq.App.Teams.AdaptiveCard/1.0.0-rc.67/Seq.App.Teams.AdaptiveCard.1.0.0-rc.67.nupkg'
2023-06-19 18:08:44    at System.IO.Strategies.FileStreamHelpers.ThrowInvalidArgument(SafeFileHandle handle)
2023-06-19 18:08:44    at System.IO.Strategies.OSFileStreamStrategy.Seek(Int64 offset, SeekOrigin origin)
2023-06-19 18:08:44    at System.IO.Strategies.BufferedFileStreamStrategy.Seek(Int64 offset, SeekOrigin origin)
2023-06-19 18:08:44    at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
2023-06-19 18:08:44    --- End of inner exception stack trace ---
2023-06-19 18:08:44    at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
2023-06-19 18:08:44    at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding)
2023-06-19 18:08:44    at System.IO.Packaging.ZipPackage..ctor(String path, FileMode packageFileMode, FileAccess packageFileAccess, FileShare share)
2023-06-19 18:08:44    at System.IO.Packaging.Package.Open(String path, FileMode packageMode, FileAccess packageAccess, FileShare packageShare)
2023-06-19 18:08:44    at Seq.Server.Features.Installation.LightweightPackageInstaller.Install(String packageFile, String directory)
2023-06-19 18:08:44    at Seq.Server.Features.Installation.AppPackageStore.GetOrInstallAsync(NuGetFeed feed, String packageId, String version, Boolean force)
2023-06-19 18:08:44    at Seq.Server.Features.Installation.AppPackageInstaller.GetOrInstallAsync(String nuGetFeedId, String packageId, String version, Boolean force)
2023-06-19 18:08:44    at Seq.Server.Features.Installation.AppPackageInstaller.InstallPackageAsync(String nuGetFeedId, String packageId, String version)
2023-06-19 18:08:44    at Seq.Server.Web.Api.AppsController.InstallPackage(String feedId, String packageId, String version)
```

I've checked  `/data/Packages/nugetfeed-438/Seq.App.Teams.AdaptiveCard/1.0.0-rc.67/Seq.App.Teams.AdaptiveCard.1.0.0-rc.67.nupkg` path and see that file doesn't exists.

Installing same nuget using file-based nuget feed succeeds, so it's not an issue in nuget itselft.

**To Reproduce**

**Environment (please complete the following information):**
 - OS: 
 - Seq Version [2023.2]: docker image [`datalust/seq:latest`](https://hub.docker.com/layers/datalust/seq/latest/images/sha256-15d5d9f69aa31d127406a39db25db6c526455c72c2f9e627b838139f87beb70b?context=explore)
 - Using Docker? Yes

Feed url : https://pkgs.dev.azure.com/macewindu/projects/_packaging/projects/nuget/v3/index.json
Feed UI: https://dev.azure.com/macewindu/projects/_artifacts/feed/projects

**Comment by nblumhardt** [comment]
Hi! Thanks for the note. I've seen this in cases where the package is intercepted by some kind of network appliance/proxy, and so the contents of the downloaded `.nupkg` file turn out to be an HTML document or some other similar thing. Is there anything between your Seq container and NuGet.org that might be doing this?

**Comment by MaceWindu** [comment]
No proxies used and feed for nuget.org works fine

**Comment by liammclennan** [comment]
@MaceWindu I'm still working on a solution, but I know what the problem is. The address of the `.nupkg` file redirects to a `*.blob.core.windows.net` domain, and Seq does not follow the redirect.

**Comment by nblumhardt** [comment]
Feed installation follows redirects in 2024.1
