### ISSUE TITLE
Load Issue on Seq 2024.3.12250

### ISSUE THREAD

**Issue by Jaben** [datalust/seq-tickets#2291]
**Describe the bug**
On Startup:

 [12:57:29 INF] Seq 2024.3.12250 running on OS Ubuntu 22.04.4 LTS
 [12:57:29 INF] Opening event store at /data/Stream/stream.flare
 [12:57:29 INF] Ingestion enabled
 [12:57:29 INF] Opening metastore /data/Documents/metastore.flare
 [12:57:29 INF] Applying migration Disable legacy event schema compatibility if possible
 [12:57:29 INF] Closing metastore
 [12:57:29 INF] Closing event store
 Application startup exception: Autofac.Core.DependencyResolutionException: An exception was thrown while activating λ:Seq.Cluster.IClusterNode -> λ:Seq.Server.StorageSubsystem.
  ---> System.ArgumentNullException: Value cannot be null. (Parameter 's')
    at System.DateTime.Parse(String s)
    at Seq.Data.Storage.Migrations.DisableLegacyEventSchemaCompatibilityIfPossible.Apply(DocumentSession session)
    at Quince.Storage.Native.NativeDocumentStore.Migrate(MigrationList migrations)
    at Seq.Server.StorageSubsystem.Initialize(IComponentContext ctx, SeqConfig config, StorageLayout layout, PerformanceCounters sharedCounters)
    at Seq.Server.SeqServerModule.<Load>b__9_10(IComponentContext c)
    at Autofac.RegistrationExtensions.<>c__DisplayClass41_0`1.<Register>b__0(IComponentContext c, IEnumerable`1 p)
    at Autofac.Builder.RegistrationBuilder.<>c__DisplayClass0_0`1.<ForDelegate>b__0(IComponentContext c, IEnumerable`1 p)
    at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
    at Autofac.Core.Activators.Delegate.DelegateActivator.<ConfigurePipeline>b__2_0(ResolveRequestContext context, Action`1 next)
    at Autofac.Core.Resolving.Middleware.DelegateMiddleware.Execute(ResolveRequestContext context, Action`1 next)
    at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
    at Autofac.Core.Resolving.Middleware.DisposalTrackingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
    at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
    at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
    --- End of inner exception stack trace ---
    at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
    at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
    at Autofac.Core.Pipeline.ResolvePipeline.Invoke(ResolveRequestContext context)
    at Autofac.Core.Resolving.Middleware.RegistrationPipelineInvokeMiddleware.Execute(ResolveRequestContext context, Action`1 next)
    at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
    at Autofac.Core.Resolving.Middleware.SharingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
    at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
    at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
    at Autofac.Core.Resolving.Middleware.CircularDependencyDetectorMiddleware.Execute(ResolveRequestContext context, Action`1 next)
    at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
    at Autofac.Extensions.DependencyInjection.KeyedServiceMiddleware.Execute(ResolveRequestContext context, Action`1 next)
    at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
    at Autofac.Core.Pipeline.ResolvePipeline.Invoke(ResolveRequestContext context)
    at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, ResolveRequest& request)
    at Autofac.Core.Resolving.ResolveOperation.ExecuteOperation(ResolveRequest& request)
    at Autofac.Core.Resolving.ResolveOperation.Execute(ResolveRequest& request)
    at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(ResolveRequest& request)
    at Autofac.Core.Container.ResolveComponent(ResolveRequest& request)
    at Autofac.Core.Container.Autofac.IComponentContext.ResolveComponent(ResolveRequest& request)
    at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
    at Autofac.ResolutionExtensions.ResolveOptionalService(IComponentContext context, Service service, IEnumerable`1 parameters)
    at Autofac.ResolutionExtensions.ResolveOptional(IComponentContext context, Type serviceType, IEnumerable`1 parameters)
    at Autofac.ResolutionExtensions.ResolveOptional(IComponentContext context, Type serviceType)
    at Autofac.Extensions.DependencyInjection.AutofacServiceProvider.GetService(Type serviceType)
    at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
    at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
    at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.ReflectionMiddlewareBinder.CreateMiddleware(RequestDelegate next)
    at Microsoft.AspNetCore.Builder.ApplicationBuilder.Build()
    at Microsoft.AspNetCore.Hosting.WebHost.BuildApplication()

**To Reproduce**
Startup Seq 2024.3.12250

**Expected behavior**
Not fail on startup.

**Screenshots**
![image](https://github.com/user-attachments/assets/98d01e0f-7dce-4300-9cbf-a572bf156ca9)

**Environment (please complete the following information):**
Docker running in OS Ubuntu 22.04.4 LTS -- Host is Ubuntu 20.

**Comment by Jaben** [comment]
My solution for now is to run 2024.2 -- which still works.

**Comment by nblumhardt** [comment]
Thanks for the report, @Jaben. We've pulled together a fix that should address this, although we're not sure of the sequence of events &mdash; backups, restores, upgrades, etc. &mdash; that put the configuration in the problematic state. The issue could have been in any version since late 5.1.x so it might have to remain a mystery (if this is a new instance please let us know, though).

I'm not sure of an ETA yet but expect it'll be within the next few weeks.

**Comment by Jaben** [comment]
I can zip the metadata and email it to you. What file should I include?

**Comment by nblumhardt** [comment]
Thanks for the offer! It should be possible to extract the value in question without sending any files, I'll just need a chance to craft a command line to extract it, which I'll take a shot at on Monday 👍

**Comment by Jaben** [comment]
I have another production SEQ instance failed to start because of this issue. Any update on a fix?

**Comment by nblumhardt** [comment]
Thanks for the update; we'll push this forward and aim to have a build out this week.

**Comment by nblumhardt** [comment]
(Closing as the fix is committed to the release branch now)

**Comment by nblumhardt** [comment]
2024.3.12680 should have this one resolved; if you still hit any problems please let us know. Thanks again for the report!

**Comment by Jaben** [comment]
Thanks, Nick!
