### ISSUE TITLE
Post-install setup wizard fails on Windows Server 2025

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-tickets#2339]
The post-install Seq Service Administration wizard is unable to complete on Windows Server 2025:

```
> WMIC USERACCOUNT WHERE Name='SeqDefaultInstance' SET PasswordExpires=FALSE
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Seq.Administration.Util.CaptiveProcess.Run(String fullExePath, String args, Action`1 writeStdout, Action`1 writeStderr, String workingDirectory, String stdin)
   at Seq.Administration.Scripting.SetupScript.RunProcess(String executable, String args, String masked, Boolean redirectStderrToStdout)
   at Seq.Administration.Scripting.InstallScript.Run(InstallScriptArgs args)
   at Seq.Administration.ConfigurationViewModel.Install()
   at Seq.Administration.ConfigurationViewModel.<>c__DisplayClass74_0.<RunTask>b__0()
```

This is because [WMIC has been deprecated](https://techcommunity.microsoft.com/blog/windows-itpro-blog/wmi-command-line-wmic-utility-deprecation-next-steps/4039242) and is disabled by default on new Windows builds.

The issue can be temporarily mitigated by enabling WMIC:

```
DISM /Online /Add-Capability /CapabilityName:WMIC
```

The wizard should use PowerShell or manipulate WMI programmatically instead.

Screenshot of the issue below:

![image](https://github.com/user-attachments/assets/186becac-b9ed-44d0-a3f1-75afc25b9873)

**Comment by nblumhardt** [comment]
It appears we only use `WMIC` for this one command, which can be replaced with:

```
net user SeqDefaultInstance /expires:never
```

**Comment by nblumhardt** [comment]
The final fix appears to be `Set-LocalUser -Name SeqDefaultInstance -PasswordNeverExpires:$True`. We'll test this out and publish a patch.
