### ISSUE TITLE
POSTing Raw Events using ?clef fails

### ISSUE THREAD

**Issue by stefansedich** [datalust/seq-tickets#677]
Using the latest docker image and attempting to post to the clef endpoint as per https://docs.getseq.net/docs/posting-raw-events I am receiving the following error:

```csharp
System.FormatException: String was not recognized as a valid Boolean.
   at System.Boolean.Parse(String value)
   at Seq.Server.Web.Api.RawEventsController.TryParseBody(ApiKey apiKey, StorageEventCreationData[]& events, String& errorMessage)
   at Seq.Server.Web.Api.RawEventsController.Ingest()
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
```

Using `?clef=true` appears to fix the issue here so it appear it is expecting me to specify the value for the parameter for it to work.

**Comment by nblumhardt** [comment]
Thanks for the report @stefansedich :+1: 

As a workaround while we sort this one out, you can pass `application/vnd.serilog.clef` as the content type instead, which works consistently across all of the Seq versions (I'm not sure whether `?clef=true` will necessarily work with 4.x).

**Comment by nblumhardt** [comment]
Fixed for the next preview.
