### ISSUE TITLE
Generic app host crash on `WARN` level name

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-tickets#689]
Via: https://github.com/datalust/seq-apps/issues/52

Feeding an event to the Email app causes it to crash and exit; stack trace:

```
System.ArgumentException: Requested value 'Warn' was not found.
   at System.Enum.EnumResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument)
   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at Serilog.Formatting.Compact.Reader.LogEventReader.ReadFromJObject(Int32 lineNumber, JObject jObject)
   at Seq.Apps.GenericHost.AppHost.<SendAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Seq.Apps.GenericHost.Program.<Main>d__0.MoveNext()
```

The generic app host should be fine with this, but it appears we've got something wrong in there.

**Comment by nblumhardt** [comment]
Fixed, new build due later today.
