### ISSUE TITLE
Diagnostic report regressions

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-tickets#711]
The 5.0 "full diagnostic report" has a couple of regressions that need to be investigated:

 * OS is simply reported as "Windows" instead of the full Windows build information
 * On Windows Server 2012 R2, some WMI-based details fail collection (in addition to the "Processor" details, which fail for some systems even in Seq 4.2's report)

**Comment by nblumhardt** [comment]
Stack trace from the failed diagnostic reporter:

```
System.TypeInitializationException: The type initializer for 'System.Management.ManagementPath' threw an exception. ---> System.TypeInitializationException: The type initializer for 'System.Management.WmiNetUtilsHelper' threw an exception. ---> System.ArgumentNullException: Value cannot be null. Parameter name: ptr
 at System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointer(IntPtr ptr, Type t)
 at System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointer[TDelegate](IntPtr ptr)
 at System.Management.WmiNetUtilsHelper.LoadDelegate[TDelegate](TDelegate& delegate_f, IntPtr hModule, String procName)
 at System.Management.WmiNetUtilsHelper..cctor() 
--- End of inner exception stack trace ---
 at System.Management.MTAHelper.IsNoContextMTA()
 at System.Management.MTAHelper.CreateInMTA(Type type)
 at System.Management.ManagementPath.CreateWbemPath(String path)
 at System.Management.ManagementPath..ctor(String path)
 at System.Management.ManagementPath..cctor()
--- End of inner exception stack trace ---
 at System.Management.ManagementScope..ctor()
 at Seq.Server.Features.Diagnostics.Wmi.Processor.GetInstances(ManagementScope mgmtScope, String condition, String[] selectedProperties)
 at Seq.Server.Features.Diagnostics.ProcessorReporter.Report(DiagnosticReport report)
 at Flare.Diagnostics.Reporting.DiagnosticReportCollector.CollectDiagnosticReport(TextWriter output)
```

**Comment by nblumhardt** [comment]
It appears these two issues are both caused by problems accessing WMI on the one particular server. There may not be anything we can do, here - closing with the expectation this will age out as we move forwards to newer Windows versions.
