### ISSUE TITLE
Linux docker image fails to start "Failed to initialize storage"

### ISSUE THREAD

**Issue by patros** [datalust/seq-tickets#724]
Similar but different to #716 

```
{"Error":"Seq is unavailable. Failed to initialize storage: Flare native storage failed (InternalError), error reading from an ingest buffer.\n   caused by: ingest buffer \"/data/Extents/2018-09-05_2018-09-12/extent.11745454384034871512062230528000000000.282706d0484b44ea8ce863ea01844091.tick\" could not be read\n   caused by: the event header is not valid\n   caused by: input buffer is shorter than the expected frame length"}
```

```
────────────────────────────────────────
  ░▒▓ Seq ── © 2018 Datalust Pty Ltd
────────────────────────────────────────

Running as server; press Ctrl+C to exit.

[04:15:17 INF] Seq "5.0.1874-pre" running on OS "Linux 4.4.0-134-generic #160-Ubuntu SMP Wed Aug 15 14:58:00 UTC 2018"
[04:15:19 INF] Seq listening on ["http://localhost/", "http://localhost:5341/"]
[04:15:19 INF] Seq using canonical URI "https://proddiseq.c2.sccl.qld.gov.au/"
[04:15:19 INF] Opening document store "/data/Documents/documents.lmdb"
[04:15:22 INF] Opening event store at "/data/Extents"
[04:15:22 INF] Available storage engines in order of preference are ["FLARE"]
[04:15:22 INF] Closing document store
[04:15:22 ERR] Uncaught exception from worker "Start background processes" ("0a681812-be64-49de-a559-3f6b249f2cf8")
Autofac.Core.DependencyResolutionException: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = TelemetryController (ReflectionActivator), Services = [Seq.Server.Features.Telemetry.TelemetryController], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = SystemSettings (ReflectionActivator), Services = [Seq.Server.Features.Settings.SystemSettings], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = IDocumentStore (DelegateActivator), Services = [Quince.IDocumentStore], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = ExternallyOwned ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = StorageSubsystem (DelegateActivator), Services = [Seq.Server.Storage.StorageSubsystem], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> Flare native storage failed (InternalError), error reading from an ingest buffer.
   caused by: ingest buffer "/data/Extents/2018-09-05_2018-09-12/extent.11745454384034871512062230528000000000.282706d0484b44ea8ce863ea01844091.tick" could not be read
   caused by: the event header is not valid
   caused by: input buffer is shorter than the expected frame length (See inner exception for details.) (See inner exception for details.) (See inner exception for details.) (See inner exception for details.) ---> Autofac.Core.DependencyResolutionException: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = SystemSettings (ReflectionActivator), Services = [Seq.Server.Features.Settings.SystemSettings], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = IDocumentStore (DelegateActivator), Services = [Quince.IDocumentStore], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = ExternallyOwned ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = StorageSubsystem (DelegateActivator), Services = [Seq.Server.Storage.StorageSubsystem], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> Flare native storage failed (InternalError), error reading from an ingest buffer.
   caused by: ingest buffer "/data/Extents/2018-09-05_2018-09-12/extent.11745454384034871512062230528000000000.282706d0484b44ea8ce863ea01844091.tick" could not be read
   caused by: the event header is not valid
   caused by: input buffer is shorter than the expected frame length (See inner exception for details.) (See inner exception for details.) (See inner exception for details.) ---> Autofac.Core.DependencyResolutionException: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = IDocumentStore (DelegateActivator), Services = [Quince.IDocumentStore], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = ExternallyOwned ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = StorageSubsystem (DelegateActivator), Services = [Seq.Server.Storage.StorageSubsystem], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> Flare native storage failed (InternalError), error reading from an ingest buffer.
   caused by: ingest buffer "/data/Extents/2018-09-05_2018-09-12/extent.11745454384034871512062230528000000000.282706d0484b44ea8ce863ea01844091.tick" could not be read
   caused by: the event header is not valid
   caused by: input buffer is shorter than the expected frame length (See inner exception for details.) (See inner exception for details.) ---> Autofac.Core.DependencyResolutionException: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = StorageSubsystem (DelegateActivator), Services = [Seq.Server.Storage.StorageSubsystem], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> Flare native storage failed (InternalError), error reading from an ingest buffer.
   caused by: ingest buffer "/data/Extents/2018-09-05_2018-09-12/extent.11745454384034871512062230528000000000.282706d0484b44ea8ce863ea01844091.tick" could not be read
   caused by: the event header is not valid
   caused by: input buffer is shorter than the expected frame length (See inner exception for details.) ---> System.Exception: Flare native storage failed (InternalError), error reading from an ingest buffer.
   caused by: ingest buffer "/data/Extents/2018-09-05_2018-09-12/extent.11745454384034871512062230528000000000.282706d0484b44ea8ce863ea01844091.tick" could not be read
   caused by: the event header is not valid
   caused by: input buffer is shorter than the expected frame length
   at Flare.Storage.Native.FlareResult.EnsureSuccess()
   at Flare.Storage.Reader.TryReadNext(Span`1 buffer)
   at Flare.Storage.Native.FlareStorageExtent.TryGetNext(Reader reader, Byte[]& buffer, ReadResult& current)
   at Flare.Storage.Native.FlareStorageExtent.Get(EventStoreRange range, RetrievalStatistics statistics, CancellationToken cancel, SharedAssets shared)+MoveNext()
   at Flare.Events.EventStore.GetFromExtents(EventStoreRange range, RetrievalStatistics stats, SegmentRange firstMissingSegmentRange, CancellationToken cancel)+MoveNext()
   at Flare.Events.EventStore.Get(EventStoreRange range, CancellationToken cancel, RetrievalStatistics statistics)+MoveNext()
   at System.Linq.Enumerable.EnumerablePartition`1.MoveNext()
   at Flare.Events.EventStore..ctor(IStorageEngine[] storageEngines, String extentsPath, WorkerPool workerPool, MemoryThresholds memoryThresholds, BroadcastChannel broadcast)
   at Seq.Server.SeqServerModule.InitStorageSubsystem(IComponentContext c)
   at Autofac.Builder.RegistrationBuilder.<>c__DisplayClass0_0`1.<ForDelegate>b__0(IComponentContext c, IEnumerable`1 p)
   at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   at Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(Guid id, Func`1 creator)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parameters)
   at Seq.Server.SeqServerModule.<>c.<Load>b__13_9(IComponentContext c)
   at Autofac.Builder.RegistrationBuilder.<>c__DisplayClass0_0`1.<ForDelegate>b__0(IComponentContext c, IEnumerable`1 p)
   at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   at Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(Guid id, Func`1 creator)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   at Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(Guid id, Func`1 creator)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Features.LazyDependencies.LazyRegistrationSource.<>c__DisplayClass5_0`1.<CreateLazyRegistration>b__1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Seq.Server.ServiceProcess.ServerService.<Start>b__12_0(CancellationToken cancel)
   at Flare.Workers.WorkerPool.<>c__DisplayClass4_0.<Run>b__0()
```

**Comment by nblumhardt** [comment]
Hi Patrick - this should be resolved in 5.0.1956-pre, now available on Docker Hub. We've fixed a bug in how Seq handles unclean shutdown of ingest buffers (which are written in the style of a transaction log, and so may contain partial data before a "commit" is synced).

It still worries us a little that your deployment generates so many of these (wondering if the storage driver might not like us! :-)); we'd love to hear how things go with the new build.
