### ISSUE TITLE
Flare native storage failed (InternalError), failed to open the key-value store at: "/data/Extents/2018-11-21_2018-11-28/extent.0.metadata".

### ISSUE THREAD

**Issue by SeriousM** [datalust/seq-tickets#777]
We run seq in our kubernetes cluster and experienced sometimes evicted pods. After the last incident we had over 700 evicted pods and after cleaning up this mess seq can't start with the error in the log below.
Is there any way to rescue the logs?

```log
 ────────────────────────────────────────
  Seq ♦ Machine data, for humans.
─────────── © 2018 Datalust Pty Ltd ────
Running as server; press Ctrl+C to exit.
[09:57:21 INF] Seq "5.0.2362" running on OS "Linux 4.15.0-1030-azure #31~16.04.1-Ubuntu SMP Tue Oct 30 19:40:01 UTC 2018"
[09:57:22 INF] Seq listening on ["http://localhost/", "http://localhost:5341/"]
[09:57:22 INF] Seq using canonical URI "xxxxxxxxxxxxxxxxx"
[09:57:23 INF] Opening document store "/data/Documents/documents.lmdb"
[09:57:24 INF] Closing document store
[09:57:24 ERR] Uncaught exception from worker "Start background processes" ("ba93e9a8-1602-4602-aacb-ff33ae2cf4f5")
Autofac.Core.DependencyResolutionException: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = TelemetryController (ReflectionActivator), Services = [Seq.Server.Features.Telemetry.TelemetryController], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = SystemSettings (ReflectionActivator), Services = [Seq.Server.Features.Settings.SystemSettings], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = IDocumentStore (DelegateActivator), Services = [Quince.IDocumentStore], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = ExternallyOwned ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = StorageSubsystem (DelegateActivator), Services = [Seq.Server.Storage.StorageSubsystem], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> Flare native storage failed (InternalError), failed to open the key-value store at: "/data/Extents/2018-11-21_2018-11-28/extent.0.metadata".
   caused by: No such file or directory (os error 2) (See inner exception for details.) (See inner exception for details.) (See inner exception for details.) (See inner exception for details.) ---> Autofac.Core.DependencyResolutionException: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = SystemSettings (ReflectionActivator), Services = [Seq.Server.Features.Settings.SystemSettings], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = IDocumentStore (DelegateActivator), Services = [Quince.IDocumentStore], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = ExternallyOwned ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = StorageSubsystem (DelegateActivator), Services = [Seq.Server.Storage.StorageSubsystem], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> Flare native storage failed (InternalError), failed to open the key-value store at: "/data/Extents/2018-11-21_2018-11-28/extent.0.metadata".
   caused by: No such file or directory (os error 2) (See inner exception for details.) (See inner exception for details.) (See inner exception for details.) ---> Autofac.Core.DependencyResolutionException: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = IDocumentStore (DelegateActivator), Services = [Quince.IDocumentStore], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = ExternallyOwned ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = StorageSubsystem (DelegateActivator), Services = [Seq.Server.Storage.StorageSubsystem], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> Flare native storage failed (InternalError), failed to open the key-value store at: "/data/Extents/2018-11-21_2018-11-28/extent.0.metadata".
   caused by: No such file or directory (os error 2) (See inner exception for details.) (See inner exception for details.) ---> Autofac.Core.DependencyResolutionException: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = StorageSubsystem (DelegateActivator), Services = [Seq.Server.Storage.StorageSubsystem], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> Flare native storage failed (InternalError), failed to open the key-value store at: "/data/Extents/2018-11-21_2018-11-28/extent.0.metadata".
   caused by: No such file or directory (os error 2) (See inner exception for details.) ---> System.Exception: Flare native storage failed (InternalError), failed to open the key-value store at: "/data/Extents/2018-11-21_2018-11-28/extent.0.metadata".
   caused by: No such file or directory (os error 2)
   at Flare.Storage.Native.FlareResult.EnsureSuccess()
   at Flare.Storage.Store.Open(String path)
   at Flare.Storage.Native.FlareStorageExtent.OpenStore()
   at Flare.Storage.Native.FlareStorageExtent..ctor(IStorageEngine storageEngine, ExtentRange range, String dataFile)
   at Flare.Storage.Native.FlareStorageEngine.CreateExtent(ExtentRange range, String dataFile, String instanceName)
   at Flare.Storage.Extents.ExtentMap..ctor(IStorageEngine[] storageEngines, String extentsPath)
   at Flare.Events.EventStore..ctor(IStorageEngine[] storageEngines, String extentsPath, WorkerPool workerPool, MemoryThresholds memoryThresholds, BroadcastChannel broadcast, IClock clock)
   at Seq.Server.SeqServerModule.InitStorageSubsystem(IComponentContext c)
   at Autofac.Builder.RegistrationBuilder.<>c__DisplayClass0_0`1.<ForDelegate>b__0(IComponentContext c, IEnumerable`1 p)
   at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   at Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(Guid id, Func`1 creator)
   at Autofac.Core.Resolving.InstanceLookup.Execute() 
```

**Comment by SeriousM** [comment]
I just updated to the latest version '5.0.2362' but still get the error. I hope we can fix the problem without reset?

**Comment by nblumhardt** [comment]
Hi Bernhard, thanks for the report.

What kind of storage are you using with your cluster? (Mounted local volumes, or something else?) Also, any idea why the mass evictions are occurring?

The nuclear option, which should preserve Seq's configuration, is to delete the `Extents/2018-11-21_2018-11-28` folder (and if this doesn't work, it's to delete `Extents`).

There should be a less destructive option, if you're able to move the problem folder out to another location and send us an `ls` of its contents. Thanks!

**Comment by SeriousM** [comment]
I tried to move the folder in question to another location but the file just was not able to read. Even chmod or chown didn't helped at all. So I tried to move the folder with azure lob storage explorer but again no luck.

"The specified resource is marked for deletion by an SMB client." is the message I got. 
Seems like azure has some problems with locks in some way: https://social.msdn.microsoft.com/Forums/expression/en-US/6ea224f1-06e6-4298-bfee-2efb69af2894/azure-file-locked-remove-the-lock-or-delete

I will investigate this further and keep you updated.

**Comment by nblumhardt** [comment]
Thanks for the follow-up, appreciate you passing on your findings :-)

We have two other customers experiencing problems with Azure Files - even oddities like pages missing from disk until the container is restarted, files appearing to not be synced when requested, etc.

It's possible that this is due to some issue with Seq's filesystem handling, but, the issues have appeared everywhere from config file writes (raw .NET System.IO) to the document store (LMDB) to (now) the event store. We haven't hit any of these issues on other filesystems so far.

I opened a Twitter thread with the Azure Files engineering manager, who suggested mounted VHDs (Azure Disks) will be a better fit for this kind of workload than the SMB-based Azure Files. A recent Microsoft product announcement introduces Azure Premium Files (no idea what backs this), and in the same announcement subtly appears to suggest Azure Files may not be a good production choice:

> It is well suited for general purpose files services and dev/test environments.

https://azure.microsoft.com/en-au/blog/a-new-era-for-azure-files-bigger-faster-better/

Taken all together, we're cautiously recommending against Azure Files for Seq data storage, but we do still have our eye out for clues as to how we might support it better.

**Comment by SeriousM** [comment]
Welcome in the new year 2019!

> I opened a Twitter thread

could you give me the url to the thread?

**Comment by nblumhardt** [comment]
Closing this one also, but as mentioned on the other ticket, please drop us a line if you need help getting back in action/migrating to Azure Disks. Thanks!
