### ISSUE TITLE
Cannot allocate memory (Container) (5.1.2976) 

### ISSUE THREAD

**Issue by AntoineGa** [datalust/seq-tickets#835]
I host Seq on as a Docker container on a CentOs VM on Azure.
After stopping my 5.0.2313 instance and created a 5.1.2976 instance, i have seen the following:
- i cannot access the diagnostics tab
- the UI shows that the server is unavailable
- the container takes 75% of the available memory (the version 5.0.2313 takes the same )
- i can see the following log:
` HTTP "GET" "/api/diagnostics/status?initial=false" responded 500 in 4.232018 ms
System.ComponentModel.Win32Exception (12): Cannot allocate memory
   at Interop.Sys.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setUser, UInt32 userId, UInt32 groupId, Int32& lpChildPid, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean shouldThrow)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Flare.Internal.OS.CaptiveProcess.Run(String fullExePath, String args, Action`1 writeStdout, Action`1 writeStderr, String workingDirectory, Boolean elevated)
   at Flare.Util.IO.DiskUtil.GetFreeSpaceBytes(String path)
   at Flare.Events.EventStore.GetMetrics()
   at Seq.Server.Web.Api.DiagnosticsController.GetServerStatus()
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Seq.Server.Web.Middleware.WebSocketAcceptMiddleware.Invoke(HttpContext context)
   at Seq.Server.Web.Middleware.RequestAuthenticationMiddleware.Invoke(HttpContext httpContext)
   at Seq.Server.Web.Middleware.BrowserSecurityOptionsMiddleware.Invoke(HttpContext context)
   at Seq.Server.Web.Middleware.RequestCompletionMiddleware.Invoke(HttpContext httpContext)
`

 I have stopped the latest one and use again the 5.0.2313 instance

**Comment by nblumhardt** [comment]
Thanks for the report, @AntoineGa - we'll dig in deeper.

How frequently does the issue occur - i.e. did it happen after some particular running time, or immediately, and just the once, or more often?

**Comment by AntoineGa** [comment]
I have just tried once.
I have started the container using the default parameter from dockerhub, reusing the same data folder. Everything seems to works fine, but i have used a bad name for the container.
So i have stopped the container, removed it, and recreated using the name i want, and then i have seen this behaviour.

**Comment by nblumhardt** [comment]
Thanks for the follow-up. It looks like this might be an I/O or memory-related issue on the host machine; the discussions I can find online seem to suggest there are intermittent/transient causes of this. Would it be possible to try running the new version again, to see whether the problem is reproducible?

**Comment by AntoineGa** [comment]
Indeed, stopping the old instance container, waiting and starting the new one did the trick.
Thanks !

**Comment by AntoineGa** [comment]
5 minutes later, the issue is back

**Comment by nblumhardt** [comment]
Thanks for the update. Is it possible to send a diagnostic log from _Settings > Diagnostics_ (even after rolling back) to support@datalust.co? Any other info that would help narrow it down would be great. We'll see if we can repro, somehow, here 👍

**Comment by AntoineGa** [comment]
Sent !

**Comment by nblumhardt** [comment]
Thanks 👍

**Comment by AntoineGa** [comment]
Setting both memory and memory-swap fixes the issue.

**Comment by Archanian** [comment]
@AntoineGa could you perhaps elaborate on how to set those? I am having this same issue

**Comment by isaiahlg** [comment]
I have just experienced this same issue.  I'm running Seq in a Docker container on Ubuntu on an Azure VM.  A memory allocation exception caused an app "appinstance-20" (Email+) to crash, and it thus then failed to send me an email alert for a critical error logged 1 minute later:
![image](https://user-images.githubusercontent.com/40040369/86265272-91439980-bb91-11ea-9f07-98d3b27ecc71.png)

The container was restarted and has since been working well. Would love to know what caused this and how to avoid it again in the future.

Full diagnostic report attached. 
[seq-diagnostics-8d81dd714e2359c.txt](https://github.com/datalust/seq-tickets/files/4858956/seq-diagnostics-8d81dd714e2359c.txt)
