### ISSUE TITLE
ArgumentException while trying to date range filter

### ISSUE THREAD

**Issue by Suchiman** [datalust/seq-tickets#886]
Did this query
`@Timestamp > Now() - 10s`
received a display worth of log, scrolled to the end to trigger seq loading more events.
Loading indicator popped up for a few seconds, then turned into an unhandled exception:
```
System.ArgumentException: The range `start` must be before or equal to the range `end`.
   at Flare.Time.DateTimeRangeBounds..ctor(Nullable`1 start, Nullable`1 end)
   at Flare.Events.EventStoreRange.GetOuterBounds()
   at Flare.Events.EventStore.Get(EventStoreRange range, CancellationToken cancel, RetrievalStatistics statistics)+MoveNext()
   at System.Linq.Enumerable.EnumerablePartition`1.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Flare.Queries.DataStore.GetFilter(Int32 count, Nullable`1 startAfter, Nullable`1 startFrom, Nullable`1 rangeStartUtc, Nullable`1 rangeEndUtc, String filter, IndexExpression indexExpression, Nullable`1 shortCircuitAfter, EventRetrievalStatistics& statistics)
   at Seq.Server.Web.Api.EventsController.QueryEvents(IndexedFilter indexedFilter, EventRetrievalStatistics& stats)
   at Seq.Server.Web.Api.EventsController.InSignal(Signal signal, Boolean excludeStats)
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Seq.Server.Web.Middleware.WebSocketAcceptMiddleware.Invoke(HttpContext context)
   at Seq.Server.Web.Middleware.RequestAuthenticationMiddleware.Invoke(HttpContext httpContext)
   at Seq.Server.Web.Middleware.HstsMiddleware.Invoke(HttpContext context)
   at Seq.Server.Web.Middleware.BrowserSecurityOptionsMiddleware.Invoke(HttpContext context)
   at Seq.Server.Web.Middleware.RequestCompletionMiddleware.Invoke(HttpContext httpContext)
```
Btw. i have `Automatically send internal error reports to Datalust` on, does it write in the log if a report has been sent?

**Comment by nblumhardt** [comment]
Thanks for the report, Robin. The API should sort out the date range overlap to prevent this error being shown to the client - we do this in a few places but seems like we've missed one, here.

Thanks for turning on error reporting. Any `"@l":"Error"` event shown in the internal log will be forwarded as an error report (though heavily redacted); I just dug through the recent data here and spotted this one :+1:
