### ISSUE TITLE
Docker image server command line cannot find configuration.

### ISSUE THREAD

**Issue by worldspawn** [datalust/seq-tickets#890]
Docker image seems to put its data in `/data`. When i shell in and try and run `/bin/seq-server/Seq config` (...which is not `seq` as your documentation states btw) I get:

```
root@f18bc8ecedbb:/# /bin/seq-server/Seq config
[03:54:24 FTL] Could not "list" config
System.IO.DirectoryNotFoundException: Could not find a part of the path '/Seq/Seq.json'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path)
   at Seq.Server.Config.SeqConfig.Read(String filename)
   at Seq.Server.Cli.ConfigCommand.Run(TextWriter cout)
```

Seq.json is in `/data/`.

**Comment by nblumhardt** [comment]
Hi Sam, thanks for the notes.

Inside the container, you'll need to pass `--storage=/data` to all `Seq` commands.

Alternatively, you can run the container with a command like so:

```
docker run --rm -it datalust/seq config
```

Does this help?

(Also, if you happen to remember where the case typo is in our docs, it would be great to know so we can track it down. Cheers!)

**Comment by worldspawn** [comment]
I'm away from my work PC atm but I think I was referring to this page - https://docs.datalust.co/docs/server-command-line

**Comment by nblumhardt** [comment]
I've updated the docs; let us know if you're still hitting any issues :-) ... thanks for this!
